using System;
using System.Linq;
using Sifon.Abstractions.Profiles;

namespace Sifon.Code.ScriptGenerators
{
    public class ParametersSampleScriptGenerator
    {
        private readonly IProfile _profile;

        public ParametersSampleScriptGenerator(IProfile profile)
        {
            _profile = profile;
        }

        public string Generate()
        {
            string script = @"### Name: Sample script exposing profile parameters
### Description: This script was generated by Profile editor

param(
    [string]$Name,
    [string]$Prefix,
    [string]$Website,
    [string]$Webroot,
    [string]$Solr,
";

foreach (var parameter in _profile.Parameters)
{
    script += $"    [string]${parameter.Key},\n";
}

script += @"
    [string]$ServerInstance,
    [string]$Username,
    [string]$Password
)

Write-Warning ""Below are all the parameters currently passed to a plugin from a profile""
Write-Output ""Feel free to remove those unused and complete your code below""
Write-Output """"

Write-Output ""Name = $Name""
Write-Output ""Prefix = $Prefix""
Write-Output ""Website = $Website""
Write-Output ""Webroot = $Webroot""
Write-Output ""Solr = $Solr""
Write-Output ""ServerInstance = $ServerInstance""
Write-Output ""Username = $Username""
Write-Output ""Password = $Password""
Write-Output """"
";
            if (_profile.Parameters.Any())
            {
                script += @"Write-Warning ""There are also additional custom parameters coming from your profile:""" + Environment.NewLine;
                foreach (var parameter in _profile.Parameters)
                {
                    script += "Write-Output \"" + parameter.Key + " = $" + parameter.Key + "\"\n";
                }
            }

            return script;
        }
    }
}
